### ISSUE TITLE
Pull cmd prefix doesn't work when briefcase cooperates with aggregate 2.0

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/aggregate#364]
#### Software and hardware versions 
Windows/Linux/macOS, Aggregate v2.0.x, Java vx.x.x, ...

#### Problem description
Pull cmd pefix doesn't work when briefcase cooperates with aggregate 2.0, screenshot of error message:
![screenshot from 2018-12-28 09-20-25](https://user-images.githubusercontent.com/33342488/50508350-d3ae8680-0a81-11e9-9b6d-0146d9d04abb.png)

#### Steps to reproduce the problem
Use -plla command to pull a form from aggregate 2.0.

#### Expected behavior
User should be able to use -plla command.

#### Other information 
Outdated pull command doesn't work as well. 
-psha command works properly
the issue might be connected to issue #363

**Comment by kkrawczyk123** [comment]
@ggalmazor, I have tried with my local tomcat instance, the newest master. Forms that I have tried to pull are - All widgets, Birds and One Page Form. (One Page Form has a 1 incomplete submission so I tried -ii prefix and it didn't work)

**Comment by ggalmazor** [comment]
OK, I can reproduce the error with your database (I have a copy of @kkrawczyk123's PostgreSQL local database), but I can't do so with my database.

Could you try to start a new database, push All Widgets and then pull it to a clean storage directory?

**Comment by ggalmazor** [comment]
OK, I think this is happening because the form with ID `build_-_1544441047` has no name. Maybe you uploaded that one while trying the new string sanitizing algorithm, and it removed all chars from the form's title?

If so, I think this is more a Briefcase issue, which would be solved by the central database. In any case, we should change the error message because it's misleading.
